[feature] 添加网易云音乐查询接口
HisAtri/LrcApi pull request #79
Opened 2024-10-12 13:21 UTC by TooAndy

添加网易云音乐查询接口. 公用数据库挂了的话, 可以用作备份.

2024-10-13 13:26 UTC, HisAtri commented
<https://github.com/HisAtri/LrcApi/pull/79/commits/2b56a983a5321600adf13d45b0c49d5fb2713cd4>

[获取封面的API](https://music.aqzscn.cn/docs/guides/interfaces#%E8%8E%B7%E5%8F%96%E5%B0%81%E9%9D%A2)应该允许Title为空的情况

>三者都传：获取歌曲封面
不传歌曲标题：获取专辑封面
只传歌手名：获取歌手图片

2024-10-13 15:41 UTC, TooAndy commented
这样的话，要用其他的接口来写了，网易云的那个 search url 直接用的话 错误太多。
有空我更新一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月13日(周日) 晚上9:26
收件人: ***@***.***&gt;;
抄送: "Andre ***@***.******@***.***&gt;;
主题: Re: [HisAtri/LrcApi] [feature] 添加网易云音乐查询接口 (PR #79)




 
2b56a98
 
获取封面的API应该允许Title为空的情况
  
三者都传：获取歌曲封面
 不传歌曲标题：获取专辑封面
 只传歌手名：获取歌手图片
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-10-14 04:10 UTC, HisAtri commented
https://github.com/HisAtri/LrcApi/blob/main/mod/textcompare.py
相似度应该可以用现成的模块，Levenshtein Distance算法实际用起来不咋样

2024-10-14 04:11 UTC, HisAtri commented
> https://github.com/HisAtri/LrcApi/blob/main/mod/textcompare.py 相似度应该可以用现成的模块，Levenshtein Distance算法实际用起来不咋样

指在当前应用场景下

2024-10-17 08:04 UTC, HisAtri requested changes
最后一个commit与PR目的无关，建议撤销，如果需要修复该问题可以新开一个PR

2024-10-17 10:16 UTC, closed without merging